seed: 42
device: cuda
epochs: 50
batch_size: 512
latent_dim: 20
n_critic: 1
lr_G: 0.0002
lr_D: 0.0001
noise_std_start: 0.05
noise_std_end: 0.0
noise_decay_epochs: 30

selection:
  scope: canada            # canada | province | metro
  provinces: [ON, BC]      # used if scope=province
  metros: [GTA]            # used if scope=metro

tables:
  - name: customers
    path: data/customers.csv
    id_like: ["customer_id"]
    min_count: 20
    min_frac: 0.005
    daily_generate: 10000
  - name: accounts
    path: data/accounts.csv
    id_like: ["account_id", "customer_id"]
    daily_generate: 25000
  - name: transactions
    path: data/transactions.csv
    id_like: ["txn_id", "account_id", "customer_id"]
    daily_generate: 200000
